on: [push]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and deploy RPM
    steps:
      - uses: actions/checkout@v2
        with:
          path: protobuf
      - uses: actions/checkout@v2
        with:
          repository: protocolbuffers/protobuf
          path: google
      - uses: actions/cache@v1
        with:
          path: google_cache
          key: ${{ runner.os }}-google-fc31
      - uses: reznikmm/fedora-ada-action@v2
        with:
          spec: protobuf/packages/protobuf.spec
      - uses: reznikmm/upload-bintray-docker-action@v2
        with:
          username: reznikmm
          repository: matreshka
          package: protobuf
          version: head-fc32
          sourcePath: x86_64/*
          override: 1
          apiKey: ${{secrets.BINTRAY_API_KEY}}
